import React,{useMemo,useState}from'react';
import{AlertTriangle,Edit3,Loader2,Sparkles,X}from'lucide-react';
import{useNavigate}from'react-router-dom';
import{createHiring,emptyCandidate,HiringCandidateInput,HiringParseResult,parseHiring}from'../services/hiringRequestService';
import{useToast}from'../context/ToastContext';

const required:Array<[keyof HiringCandidateInput,string,string?]>=[['candidateName','Candidate name'],['candidateEmail','Candidate email','email'],['jobTitle','Job title'],['department','Department'],['annualPackageLPA','Package (LPA)','number'],['joiningDate','Joining date','date'],['reportingManagerName','Reporting manager'],['hiringManagerName','Hiring manager'],['location','Location'],['employmentType','Employment type']];
const err=(e:any)=>e.response?.data?.detail||e.response?.data?.message||e.message||'Request failed.';
export default function HiringCommandCenter(){
 const nav=useNavigate(),{showToast}=useToast();const[instruction,setInstruction]=useState(''),[result,setResult]=useState<HiringParseResult|null>(null),[candidate,setCandidate]=useState<HiringCandidateInput|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const missing=useMemo(()=>{if(!candidate)return[];const blank=(v:unknown)=>v==null||(typeof v==='string'&&!v.trim());const values:Array<[string,unknown]>=[['candidateName',candidate.candidateName],['candidateEmail',candidate.candidateEmail],['jobTitle',candidate.jobTitle],['department',candidate.department],['annualPackageLPA',candidate.annualPackageLPA],['joiningDate',candidate.joiningDate],['reportingManagerName',candidate.reportingManagerName],['hiringManagerName',candidate.hiringManagerName],['location',candidate.location],['employmentType',candidate.employmentType]];const absent=values.filter(([,v])=>blank(v)||(typeof v==='number'&&(!Number.isFinite(v)||v<=0))).map(([k])=>k);if(!blank(candidate.candidateEmail)&&!/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/.test(candidate.candidateEmail.trim()))absent.push('candidateEmail');if(!blank(candidate.joiningDate)&&Number.isNaN(Date.parse(candidate.joiningDate)))absent.push('joiningDate');return[...new Set(absent)];},[candidate]);
 const parse=async()=>{setBusy(true);setError('');try{const r=await parseHiring(instruction);setResult(r);setCandidate({...emptyCandidate(),...r.candidate});}catch(e){setError(err(e));setCandidate(emptyCandidate());}finally{setBusy(false)}};
 const set=(k:keyof HiringCandidateInput,v:string)=>setCandidate(c=>c?{...c,[k]:k==='annualPackageLPA'||k==='annualSalaryAmount'?(v===''?null:Number(v)):v}:c);
 const create=async()=>{if(!candidate)return;setBusy(true);setError('');try{const r=await createHiring(candidate,instruction,result?.candidate);showToast('Hiring workflow created','success','Policy validated and routed securely');nav('/hiring-requests/'+r.id);}catch(e){setError(err(e));}finally{setBusy(false)}};
 return <div className="space-y-6 text-slate-200">
  <div className="border-b border-slate-800 pb-5"><p className="text-[10px] font-mono uppercase tracking-widest text-cyan-400">AI hiring workflow</p><h1 className="text-3xl font-extrabold text-white mt-2">Nova Hiring Copilot</h1><p className="text-sm text-slate-400 mt-2">Gemini extracts the instruction. Nova validates it before creating a draft.</p></div>
  <section className="bg-slate-900 border border-slate-800 rounded-2xl p-6"><textarea rows={7} value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="Hire Sharma as a Software Engineer with a salary of 12 LPA..." className="w-full bg-slate-950 border border-slate-800 rounded-xl p-4 text-sm outline-none focus:border-cyan-500/50"/><button disabled={busy||!instruction.trim()} onClick={parse} className="mt-4 flex items-center gap-2 bg-cyan-500 text-slate-950 px-5 py-3 rounded-xl text-xs font-bold disabled:opacity-40">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Sparkles className="h-4 w-4"/>}Understand instruction</button></section>
  {error&&<div className="bg-rose-500/10 border border-rose-500/20 rounded-xl p-4 text-sm text-rose-300 flex gap-2"><AlertTriangle className="h-5 w-5 shrink-0"/>{error}</div>}
  {candidate&&missing.length>0&&<div className="bg-amber-500/10 border border-amber-500/20 rounded-xl p-5"><strong className="text-amber-300">More information required</strong><p className="text-sm text-slate-300 mt-3">Complete or correct {missing.map(key=>required.find(([field])=>field===key)?.[1]||key).join(', ')} before creating the request.</p></div>}
  {candidate&&<section className="bg-slate-900 border border-slate-800 rounded-2xl p-6">
   <div className="flex justify-between gap-4"><div><h2 className="font-bold text-white">Confirmation card</h2><p className="text-xs text-slate-400 mt-1">Review every field. No request exists until you confirm.</p></div>{result&&<div className="text-right text-xs font-mono"><p className="text-cyan-400">AI Extraction Confidence: {Math.round(result.confidence*100)}%</p><p className={missing.length?'text-amber-300 mt-1':'text-emerald-300 mt-1'}>Data Completeness: {missing.length?'Missing '+missing.length+' field'+(missing.length===1?'':'s'):'Complete'}</p></div>}</div>
   <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mt-5">{required.map(([k,label,type])=><label key={k} className="text-xs text-slate-400">{label}<input type={type||'text'} value={(candidate[k]as string|number|null)??''} onChange={e=>set(k,e.target.value)} className="mt-2 w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2.5 text-white"/></label>)}</div>
   <div className="flex flex-wrap justify-end gap-3 mt-6"><button onClick={()=>{setCandidate(null);setResult(null)}} className="flex gap-2 px-4 py-2 text-xs text-slate-400"><X className="h-4 w-4"/>Cancel</button><button onClick={()=>document.querySelector<HTMLTextAreaElement>('textarea')?.focus()} className="flex gap-2 px-4 py-2 border border-slate-700 rounded-xl text-xs"><Edit3 className="h-4 w-4"/>Edit details</button><button disabled={busy||missing.length>0} onClick={create} className="bg-emerald-500 text-slate-950 px-5 py-2.5 rounded-xl text-xs font-bold disabled:opacity-40">Create Hiring Request</button></div>
  </section>}
 </div>;
}
