import React,{useEffect,useState} from 'react';
import {FileText,Loader2,Plus} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {HiringRequest,listHiring} from '../services/hiringRequestService';

const badge=(s:string)=>s.replace(/_/g,' ');
export default function HiringRequests(){const nav=useNavigate();const[items,setItems]=useState<HiringRequest[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{listHiring().then(setItems).catch(e=>setError(e.response?.data?.detail||e.message)).finally(()=>setLoading(false));},[]);
 return <div className="space-y-6 text-slate-200"><div className="flex flex-wrap justify-between gap-3 border-b border-slate-800 pb-5"><div><h1 className="text-3xl font-extrabold text-white">Hiring Requests</h1><p className="text-sm text-slate-400 mt-2">Drafts, assigned approvals, PDFs and delivery status from Firestore.</p></div><button onClick={()=>nav('/chat')} className="flex items-center gap-2 bg-cyan-500 text-slate-950 px-4 py-2 rounded-xl text-xs font-bold"><Plus className="h-4 w-4"/>New request</button></div>
 {loading?<Loader2 className="animate-spin text-cyan-400"/>:error?<p className="text-rose-400">{error}</p>:items.length===0?<div className="bg-slate-900 border border-slate-800 rounded-2xl p-10 text-center text-slate-500"><FileText className="mx-auto mb-3"/>No hiring requests.</div>:<div className="grid gap-3">{items.map(x=><button key={x.id} onClick={()=>nav('/hiring-requests/'+x.id)} className="text-left bg-slate-900 border border-slate-800 hover:border-cyan-500/30 rounded-2xl p-5 flex flex-wrap justify-between gap-4"><div><strong className="text-white">{x.candidateName}</strong><p className="text-xs text-slate-400 mt-1">{x.jobTitle} · ₹{x.annualPackageLPA} LPA · joins {x.joiningDate}{x.emailStatus && <span className={`ml-2 text-[10px] font-semibold px-2 py-0.5 rounded ${x.emailStatus === "SENT" ? "bg-emerald-500/10 text-emerald-400" : x.emailStatus === "FAILED" ? "bg-rose-500/10 text-rose-400" : "bg-slate-800 text-slate-400"}`}>Email: {x.emailStatus}</span>}</p><p className="text-[10px] text-slate-500 mt-2">Manager: {x.hiringManagerName} · Created by {x.createdByName}</p></div><span className="text-[10px] font-mono text-cyan-400 border border-cyan-500/20 rounded-full px-3 py-1 h-fit">{badge(x.status)}</span></button>)}</div>}</div>}
