import React,{useMemo}from'react';
import{useNavigate}from'react-router-dom';
import{motion}from'framer-motion';
import{Users,GitBranch,Award,BrainCircuit,RefreshCw,Activity}from'lucide-react';
import{useAppContext}from'../context/AppContext';
import dashboardService from'../services/dashboardService';
import StatCard from'../components/StatCard';
import TrendChart from'../components/TrendChart';
import HiringPipeline from'../components/HiringPipeline';
import ActivityFeed from'../components/ActivityFeed';
import CandidateList from'../components/CandidateList';
import ApprovalInbox from'../components/ApprovalInbox';
import DashboardStatusCounts from'../components/DashboardStatusCounts';
import { formatNormalizedDate } from '../lib/dateUtils';

export const HrAdminDashboard:React.FC=()=>{
 const navigate=useNavigate();
 const{candidates,kpis,activities,refreshDashboard,loading,backendOnline,lastSync,selectCandidate}=useAppContext();
 const pipeline=useMemo(()=>dashboardService.computePipelineFromCandidates(candidates),[candidates]);
 const trend=useMemo(()=>dashboardService.getTrendData(candidates),[candidates]);
 const feed=useMemo(()=>activities.slice(0, 5).map(item=>({id:item.id,candidateName:item.sub||'NovaOS Copilot',position:item.type==='success'?'Completed':'Live operation',action:item.message,timestamp:formatNormalizedDate(item.timestamp),status:item.type==='warning'||item.type==='error'?'warning':item.type==='success'?'completed':'info'}as const)),[activities]);
 if(loading.app)return <div className="space-y-6 animate-pulse"><div className="h-12 bg-slate-900 rounded-xl w-1/3"/><div className="grid grid-cols-1 md:grid-cols-4 gap-6">{[1,2,3,4].map(i=><div key={i} className="h-28 bg-slate-900 rounded-2xl"/>)}</div><div className="h-[380px] bg-slate-900 rounded-3xl"/></div>;
 return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="space-y-8 bg-slate-950 text-slate-200">
  <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-6"><div><h1 className="text-3xl font-extrabold text-white">Employee <span className="text-cyan-500">Copilot</span></h1><p className="text-gray-400 text-sm mt-1">Live hiring operations across every NovaOS module.</p></div><div className="flex items-center gap-3"><button onClick={refreshDashboard} disabled={loading.dashboard} className="p-2.5 bg-slate-900 border border-slate-800 rounded-xl"><RefreshCw className={`h-4 w-4 ${loading.dashboard?'animate-spin':''}`}/></button><div className="flex items-center gap-2 bg-slate-900 border border-slate-800 px-4 py-2 rounded-xl text-xs font-mono"><span className={`h-2 w-2 rounded-full ${backendOnline?'bg-emerald-400':'bg-rose-400'}`}/>{backendOnline?'LIVE STATE CONNECTED':'OFFLINE SIMULATION'}{lastSync&&<span className="text-slate-500">· {formatNormalizedDate(lastSync)}</span>}</div></div></div>
  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"><StatCard title="Total Candidates" value={kpis.totalCandidates} change="Shared talent graph" icon={Users} gradient="from-blue-600/10 to-cyan-500/5"/><StatCard title="Pending Approvals" value={kpis.pendingApprovals} change="Awaiting hiring action" icon={GitBranch} gradient="from-violet-600/10 to-purple-500/5"/><StatCard title="Offers Sent" value={kpis.offersSent} change="Generated by workflow" icon={Award} gradient="from-amber-600/10 to-yellow-500/5"/><StatCard title="Employees Created" value={kpis.employeesCreated} change={`${kpis.executionsToday} executions today`} icon={BrainCircuit} gradient="from-emerald-600/10 to-teal-500/5"/></div>
  <DashboardStatusCounts />
  <ApprovalInbox />
  <HiringPipeline stages={pipeline}/>
  <div className="grid grid-cols-1 xl:grid-cols-3 gap-8"><div className="xl:col-span-2"><TrendChart data={trend}/></div><ActivityFeed activities={feed}/></div>
  <div className="bg-slate-900 border border-slate-800 p-6 rounded-3xl"><div className="flex items-center justify-between mb-5"><div><h3 className="font-bold text-white flex items-center gap-2"><Activity className="h-4 w-4 text-cyan-500"/>Live Candidate Directory</h3><p className="text-xs text-slate-400 mt-1">Selecting a record updates Candidate Intelligence globally.</p></div><button onClick={()=>navigate('/recruitment')} className="text-xs text-cyan-400 font-mono">Open Pipeline →</button></div><div className="h-[300px]"><CandidateList candidates={candidates.slice(0,8).map(c=>({id:c.id,name:c.name,role:c.role,score:c.matchScore}))} onSelect={id=>{selectCandidate(id);navigate('/intelligence')}}/></div></div>
 </motion.div>;
};
export default HrAdminDashboard;
