import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Loader2, Plus, Save, Shield } from 'lucide-react';
import { createLegalPolicy, LegalPolicy, listLegalPolicies, updateLegalPolicy } from '../services/legalService';
import { useToast } from '../context/ToastContext';

const blank:Partial<LegalPolicy>={policyId:'',title:'',description:'',category:'OFFER_LETTER',severity:'MEDIUM',active:true,mandatory:true,policyType:'COMPANY_POLICY'};
export default function LegalPolicyManager(){
 const {showToast}=useToast();const [items,setItems]=useState<LegalPolicy[]>([]);const [editing,setEditing]=useState<Partial<LegalPolicy>|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
 const load=()=>listLegalPolicies(true).then(setItems).finally(()=>setLoading(false));useEffect(()=>{void load();},[]);
 const save=async()=>{if(!editing?.policyId||!editing.title||!editing.description){showToast('Policy ID, title, and description are required.','error');return;}setBusy(true);try{if(editing.id)await updateLegalPolicy(editing.id,editing);else await createLegalPolicy(editing);showToast(editing.id?'Policy updated and version advanced.':'Policy created.','success');setEditing(null);await load();}catch(e:any){showToast(e.response?.data?.message||'Policy could not be saved.','error');}finally{setBusy(false);}};
 return <div className="space-y-6 text-slate-200"><div className="flex flex-wrap justify-between gap-4 border-b border-slate-800 pb-6"><div><h1 className="text-3xl font-extrabold text-white flex items-center gap-3"><Shield className="text-cyan-400"/>Legal Policy Management</h1><p className="text-sm text-slate-400 mt-2">Versioned internal company policies. Deactivate used policies instead of deleting them.</p></div><button onClick={()=>setEditing({...blank})} className="h-fit bg-cyan-500 text-slate-950 px-4 py-2.5 rounded-xl text-xs font-bold"><Plus className="inline h-4 w-4 mr-2"/>New Policy</button></div>
 {editing&&<section className="bg-slate-900 border border-cyan-500/20 rounded-2xl p-5 grid md:grid-cols-2 gap-3"><input disabled={Boolean(editing.id)} value={editing.policyId||''} onChange={e=>setEditing({...editing,policyId:e.target.value})} placeholder="Policy ID (e.g. OFFER-002)" className="bg-slate-950 border border-slate-700 rounded-xl p-3 text-xs disabled:opacity-50"/><input value={editing.title||''} onChange={e=>setEditing({...editing,title:e.target.value})} placeholder="Policy title" className="bg-slate-950 border border-slate-700 rounded-xl p-3 text-xs"/><input value={editing.category||''} onChange={e=>setEditing({...editing,category:e.target.value})} placeholder="Category" className="bg-slate-950 border border-slate-700 rounded-xl p-3 text-xs"/><select value={editing.severity} onChange={e=>setEditing({...editing,severity:e.target.value as LegalPolicy['severity']})} className="bg-slate-950 border border-slate-700 rounded-xl p-3 text-xs">{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select><textarea value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})} placeholder="Policy description" rows={3} className="md:col-span-2 bg-slate-950 border border-slate-700 rounded-xl p-3 text-xs"/><div className="flex gap-5 text-xs"><label><input type="checkbox" checked={editing.mandatory} onChange={e=>setEditing({...editing,mandatory:e.target.checked})} className="mr-2"/>Mandatory</label><label><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})} className="mr-2"/>Active</label></div><div className="flex justify-end gap-2"><button onClick={()=>setEditing(null)} className="border border-slate-700 px-4 rounded-lg text-xs">Cancel</button><button disabled={busy} onClick={save} className="bg-cyan-500 text-slate-950 px-4 py-2 rounded-lg text-xs font-bold"><Save className="inline h-3 w-3 mr-2"/>{busy?'Saving...':'Save Policy'}</button></div></section>}
 {loading?<Loader2 className="animate-spin text-cyan-400"/>:<div className="grid lg:grid-cols-2 gap-4">{items.map((p,i)=><motion.button initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} transition={{delay:i*.02}} onClick={()=>setEditing({...p})} key={p.policyId} className={`text-left bg-slate-900 border rounded-2xl p-5 ${p.active?'border-slate-800 hover:border-cyan-500/30':'border-slate-800 opacity-55'}`}><div className="flex justify-between gap-4"><div><p className="text-[10px] font-mono text-cyan-400">{p.policyId} · v{p.version}</p><h2 className="font-bold text-white mt-1">{p.title}</h2></div><div className="text-right"><span className="text-[9px] border border-slate-600 rounded-full px-2 py-1">{p.severity}</span><p className="text-[9px] text-slate-500 mt-2">{p.active?'ACTIVE':'INACTIVE'} · {p.mandatory?'MANDATORY':'OPTIONAL'}</p></div></div><p className="text-xs text-slate-400 mt-3 leading-relaxed">{p.description}</p><p className="text-[10px] text-violet-300 mt-3">{p.policyType==='COMPANY_POLICY'?'Company Policy':p.policyType}</p></motion.button>)}</div>}</div>;
}
