import React, { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { AlertTriangle, CheckCircle2, Loader2, ShieldCheck, XCircle } from 'lucide-react';
import { approveLegalReview, getLegalReview, LegalReview, rejectLegalReview, RiskLevel } from '../services/legalService';
import { HiringRequest } from '../services/hiringRequestService';
import { useToast } from '../context/ToastContext';

const label=(value:string)=>value.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const styles:Record<RiskLevel,string>={LOW:'text-emerald-300 border-emerald-500/30 bg-emerald-500/10',MEDIUM:'text-amber-300 border-amber-500/30 bg-amber-500/10',HIGH:'text-rose-300 border-rose-500/30 bg-rose-500/10'};
const summaryFields=['candidateName','jobTitle','department','annualPackageLPA','joiningDate','employmentType','noticePeriod','probationPeriod'];

export default function LegalPolicyReview({requestId,onDecision,onBackendUnavailable}:{requestId:string;onDecision:(item:HiringRequest)=>void;onBackendUnavailable?:(unavailable:boolean)=>void}) {
  const {showToast}=useToast();
  const [review,setReview]=useState<LegalReview|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const [modal,setModal]=useState<'approve'|'reject'|null>(null); const [approvalComment,setApprovalComment]=useState(''); const [rejectionReason,setRejectionReason]=useState('');
  useEffect(()=>{setLoading(true);getLegalReview(requestId).then(value=>{setReview(value);onBackendUnavailable?.(Boolean(value.backendUnavailable));}).catch((e:any)=>setError(e.response?.data?.message||'Legal risk review could not be loaded.')).finally(()=>setLoading(false));},[requestId,onBackendUnavailable]);
  const summary=useMemo(()=>review?.summary||{LOW:0,MEDIUM:0,HIGH:0,TOTAL:0},[review]);
  const decide=async(type:'approve'|'reject')=>{if(type==='reject'&&!rejectionReason.trim())return;setBusy(true);setError('');try{const item=type==='approve'?await approveLegalReview(requestId,approvalComment.trim()):await rejectLegalReview(requestId,rejectionReason.trim());onDecision(item);setModal(null);showToast(type==='approve'?'Legal approval recorded. The policy risks were advisory only.':'Candidate rejected. The workflow was terminated and the backend processed the notification.','success');}catch(e:any){const message=e.response?.data?.message||`Legal ${type} could not be completed.`;setError(message);showToast(message,'error');}finally{setBusy(false);}};
  if(loading)return <section className="bg-slate-900 border border-slate-800 rounded-2xl p-10 flex justify-center"><Loader2 className="animate-spin text-cyan-400"/></section>;
  if(!review)return <section className="bg-rose-500/10 border border-rose-500/20 rounded-2xl p-5 text-sm text-rose-300">{error}</section>;
  return <motion.section initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="bg-slate-900 border border-cyan-500/20 rounded-2xl p-6 space-y-6">
    <div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-xl font-bold text-white flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-cyan-400"/>Legal Risk Summary</h2><p className="text-xs text-slate-400 mt-1">Internal company-policy guidance only. Legal always makes the final decision.</p></div><div className={`border rounded-xl px-5 py-3 text-center ${styles[review.overallRisk]}`}><p className="text-[10px] uppercase tracking-wider">Overall risk</p><strong className="text-lg">{review.overallRisk}</strong></div></div>
    <div className="grid grid-cols-3 gap-3">{(['LOW','MEDIUM','HIGH'] as RiskLevel[]).map(level=><div key={level} className={`rounded-xl border p-3 text-center ${styles[level]}`}><strong className="text-xl">{summary[level]}</strong><p className="text-[10px] mt-1">{label(level)} Risk</p></div>)}</div>
    <div><h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-3">Candidate information</h3><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{summaryFields.map(field=><div key={field} className="bg-slate-950 border border-slate-800 rounded-xl p-3"><p className="text-[9px] uppercase text-slate-500">{label(field==='annualPackageLPA'?'salary':field)}</p><p className="text-xs text-white mt-1 break-words">{review.candidateSummary[field]!==null&&review.candidateSummary[field]!==undefined&&review.candidateSummary[field]!==''?String(review.candidateSummary[field])+(field==='annualPackageLPA'?' LPA':''):'Not provided'}</p></div>)}</div></div>
    {review.backendUnavailable&&<div className="flex gap-3 rounded-xl border border-amber-500/20 bg-amber-500/10 p-4"><AlertTriangle className="h-5 w-5 text-amber-400 shrink-0"/><p className="text-xs text-amber-100/80">Policy preview only. Restart the updated backend to calculate live candidate risks and make a decision.</p></div>}
    {error&&<p className="rounded-xl border border-rose-500/20 bg-rose-500/10 p-3 text-xs text-rose-300">{error}</p>}
    <div><h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-3">Legal policy review</h3><div className="grid xl:grid-cols-2 gap-4">{review.policyResults.map((policy,index)=><motion.article key={policy.policyId} initial={{opacity:0}} animate={{opacity:1}} transition={{delay:index*.035}} className="bg-slate-950 border border-slate-800 rounded-xl p-4"><div className="flex justify-between gap-3"><div><p className="text-[10px] font-mono text-cyan-400">{policy.policyId}</p><h4 className="text-sm font-bold text-white mt-1">{policy.title}</h4></div><span className={`h-fit text-[10px] font-bold border rounded-full px-2.5 py-1 ${styles[policy.riskLevel]}`}>{policy.riskLevel}</span></div><div className="grid grid-cols-2 gap-3 my-4"><div><p className="text-[9px] uppercase text-slate-500">Current value</p><p className="text-xs text-white mt-1">{policy.currentValue}</p></div><div><p className="text-[9px] uppercase text-slate-500">Company policy</p><p className="text-xs text-white mt-1">{policy.policyValue}</p></div></div><p className="text-xs text-slate-400 leading-relaxed">{policy.explanation}</p></motion.article>)}</div></div>
    <div className="border-t border-slate-800 pt-5"><p className="text-xs text-slate-500 mb-4">Medium and high risks never block approval automatically.</p><div className="flex gap-3"><button disabled={busy||review.backendUnavailable} onClick={()=>setModal('approve')} className="bg-emerald-500 disabled:opacity-40 text-slate-950 px-5 py-3 rounded-xl text-xs font-bold"><CheckCircle2 className="inline h-4 w-4 mr-2"/>Approve</button><button disabled={busy||review.backendUnavailable} onClick={()=>setModal('reject')} className="bg-rose-600 disabled:opacity-40 text-white px-5 py-3 rounded-xl text-xs font-bold"><XCircle className="inline h-4 w-4 mr-2"/>Reject</button></div></div>
    <AnimatePresence>{modal&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4" onMouseDown={()=>!busy&&setModal(null)}><motion.div initial={{scale:.96,y:12}} animate={{scale:1,y:0}} exit={{scale:.96,y:12}} onMouseDown={e=>e.stopPropagation()} className={`w-full max-w-lg bg-slate-900 border rounded-2xl p-6 shadow-2xl ${modal==='approve'?'border-emerald-500/30':'border-rose-500/30'}`}><h2 className="text-xl font-bold text-white">{modal==='approve'?'Approve Candidate':'Reject Candidate'}</h2><p className="text-sm text-slate-400 mt-2">Candidate: <strong className="text-white">{String(review.candidateSummary.candidateName||'Candidate')}</strong></p><label className="block text-xs font-bold text-slate-300 mt-5 mb-2">{modal==='approve'?'Reviewer comment (optional)':'Reason for rejection (required)'}</label><textarea autoFocus rows={5} value={modal==='approve'?approvalComment:rejectionReason} onChange={e=>modal==='approve'?setApprovalComment(e.target.value):setRejectionReason(e.target.value)} placeholder={modal==='approve'?'Enter approval comment...':'Enter the reason for rejecting this candidate...'} className="w-full bg-slate-950 border border-slate-700 rounded-xl p-3 text-sm text-white outline-none"/>{modal==='reject'&&<p className="text-[10px] text-slate-500 mt-2">This internal reason is never included in the candidate email.</p>}<div className="flex justify-end gap-3 mt-6"><button disabled={busy} onClick={()=>setModal(null)} className="border border-slate-700 text-slate-300 px-4 py-2.5 rounded-xl text-xs">Cancel</button><button disabled={busy||(modal==='reject'&&!rejectionReason.trim())} onClick={()=>decide(modal)} className={`${modal==='approve'?'bg-emerald-500 text-slate-950':'bg-rose-600 text-white'} disabled:opacity-40 px-4 py-2.5 rounded-xl text-xs font-bold`}>{busy?<><Loader2 className="inline h-4 w-4 animate-spin mr-2"/>Saving...</>:modal==='approve'?'Confirm Approval':'Reject Candidate'}</button></div></motion.div></motion.div>}</AnimatePresence>
  </motion.section>;
}
